service: brose-films-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    EMAIL_USER: brosefilmsproduction@gmail.com
    EMAIL_PASS: ${env:EMAIL_PASS, 'placeholder'}

package:
  patterns:
    - 'lambda-minimal/**'
    - '!node_modules/**'
    - '!client/**'
    - '!server/**'
    - '!src/**'
    - '!public/**'
    - '!pictures/**'
    - '!aws-lambda/**'
    - '!.git/**'
    - '!.serverless/**'
    - '!*.zip'
    - '!*.md'

functions:
  contact:
    handler: lambda-minimal/index.handler
    events:
      - http:
          path: api/contact
          method: post
          cors: true
      - http:
          path: api/contact
          method: options
          cors: true
